/* #region ERROR CODES */
#define ESP_ERR_MEASUREMENT_TASK_BASE 0x7000U

#define ESP_ERR_INVALID_POLLING_RATE (ESP_ERR_MEASUREMENT_TASK_BASE + 1U)
#define ESP_ERR_INVALID_STACK_DEPTH (ESP_ERR_MEASUREMENT_TASK_BASE + 2U)
#define ESP_ERR_INVALID_CORE_ID (ESP_ERR_MEASUREMENT_TASK_BASE + 3U)
#define ESP_ERR_INVALID_PRIORITY (ESP_ERR_MEASUREMENT_TASK_BASE + 4U)
#define ESP_ERR_INVALID_PC_NAME (ESP_ERR_MEASUREMENT_TASK_BASE + 5U)
#define ESP_ERR_INVALID_MEASUREMENT_TASK (ESP_ERR_MEASUREMENT_TASK_BASE + 6U)

#define ESP_ERR_INIT_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 7U)
#define ESP_ERR_START_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 8U)
#define ESP_ERR_STOP_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 9U)
#define ESP_ERR_RESET_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 10U)

#define ESP_ERR_MEASUREMENT_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 11U)

#define ESP_ERR_TASK_NOT_CONFIGURED (ESP_ERR_MEASUREMENT_TASK_BASE + 12U)

#define ESP_ERR_TASK_NAME_TAKEN (ESP_ERR_MEASUREMENT_TASK_BASE + 13U)

#define ESP_ERR_TASK_CREATE_FAIL (ESP_ERR_MEASUREMENT_TASK_BASE + 14U)

#define ESP_ERR_IS_RUNNING (ESP_ERR_MEASUREMENT_TASK_BASE + 15U)
#define ESP_ERR_NOT_RUNNING (ESP_ERR_MEASUREMENT_TASK_BASE + 16U)

#define ESP_ERR_TASK_NOT_FOUND (ESP_ERR_MEASUREMENT_TASK_BASE + 17U)

#define ESP_ERR_MEASUREMENT_TASK_END 0x7100
/* #endregion */