#pragma once
#ifndef EVENTSYSTEMERRORS_H
#define EVENTSYSTEMERRORS_H

#define ESP_ERR_EVENT_SYSTEM_BASE 0x7500U

#define ESP_ERR_MAX_EVENT_HANDLERS (ESP_ERR_EVENT_SYSTEM_BASE + 1U)
#define ESP_ERR_NO_EVENT_HANDLERS (ESP_ERR_EVENT_SYSTEM_BASE + 2U)
#define ESP_ERR_EVENT_HANDLER_NOT_FOUND (ESP_ERR_EVENT_SYSTEM_BASE + 3U)
#define ESP_ERR_ACCESS_WAIT_TIMEOUT (ESP_ERR_EVENT_SYSTEM_BASE + 4U)
#define ESP_ERR_RECEIVE_WAIT_TIMEOUT (ESP_ERR_EVENT_SYSTEM_BASE + 5U)
#define ESP_ERR_SEND_WAIT_TIMEOUT (ESP_ERR_EVENT_SYSTEM_BASE + 6U)
#define ESP_ERR_RING_BUFF_CREATE_FAIL (ESP_ERR_EVENT_SYSTEM_BASE + 7U)
#define ESP_ERR_RING_BUFF_SEND_FAIL (ESP_ERR_EVENT_SYSTEM_BASE + 8U)
// #define ESP_ERR_ACCESS_MUX_TIMEOUT (ESP_ERR_EVENT_SYSTEM_BASE + 3U)

#endif