#pragma once
#ifndef BME6XXMANAGERERRORS_H
#define BME6XXMANAGERERRORS_H

#define ESP_ERR_BME_MNGR_BASE 0x7700U

#define ESP_ERR_MAX_NUM_SENSORS (ESP_ERR_BME_MNGR_BASE + 1U)
#define ESP_ERR_NO_SENSORS (ESP_ERR_BME_MNGR_BASE + 2U)
#define ESP_ERR_INITIALIZATION_FAILED (ESP_ERR_BME_MNGR_BASE + 3U)
#define ESP_ERR_BUFFER_DATA_ERROR (ESP_ERR_BME_MNGR_BASE + 4U)
#define ESP_ERR_BME6XX_DRIVER_ERROR (ESP_ERR_BME_MNGR_BASE + 5U)
#define ESP_ERR_CONFIG_FILE_ERROR (ESP_ERR_BME_MNGR_BASE + 6U)
#define ESP_ERR_SENSOR_INDEX_ERROR (ESP_ERR_BME_MNGR_BASE + 7U)
#define ESP_ERR_JSON_DESERIAL_ERROR (ESP_ERR_BME_MNGR_BASE + 8U)
#define ESP_ERR_JSON_FORMAT_ERROR (ESP_ERR_BME_MNGR_BASE + 9U)
#define ESP_ERR_SENSOR_NOT_FOUND (ESP_ERR_BME_MNGR_BASE + 10U)
#define ESP_ERR_SENSOR_DATA_MISS (ESP_ERR_BME_MNGR_BASE + 11U)
#define ESP_ERR_SENSOR_STATE_INVALID (ESP_ERR_BME_MNGR_BASE + 12U)
#define ESP_ERR_BME_MNGR_STATE_INVALID (ESP_ERR_BME_MNGR_BASE + 13U)
#define ESP_ERR_SENSOR_NO_NEW_DATA (ESP_ERR_BME_MNGR_BASE + 14U)

#endif