#pragma once
#ifndef TGS_SAMPLE_MODULE_CONFIG_H
#define TGS_SAMPLE_MODULE_CONFIG_H

#include "soc/gpio_num.h"

#define TGS2602_HEATER_CONTROL_PIN        GPIO_NUM_5
#define TGS2602_HEATER_WARMUP_DURATION_MS 120000U

#define TASK_QUEUE_SEND_TIMEOUT_MS 1000U

#define TASK_TGS2602_SAMPLING_SAMPLE_PERIOD_MS 62U

#endif